### ISSUE TITLE
Link to data files missing

### ISSUE THREAD

**Issue by mdeboc** [takat0m0/AAE#1]
e.g. 'mnist_test.csv'

> IOError: [Errno 2] No such file or directory: 'mnist_test.csv'

**Comment by takat0m0** [comment]
Thank you for your pointing  out.
I'd like to write usage of this program in README.md.
In order to use this program, we must prepare MNIST data with csv format, which can be made by  https://pjreddie.com/projects/mnist-in-csv/  .
Please wait for my modifying the README.md.
