### ISSUE TITLE
Question about conv_layer and deconv_layer

### ISSUE THREAD

**Issue by mszeto715** [takat0m0/AAE#4]
Hi,

First, Thank you for sharing this code!

Second, I was wondering if you have tried anything using the conv_layer and deconv_layer functions in the encoder and decoder to switch to a CNN. I have tried but can't seem to get the tensors to all fit nicely.

-Mimi

**Comment by takat0m0** [comment]
Hi, Mimi.

Thank you for your pointing out. I'd like to try to make AAE with CNN. 

Maybe, using the conv_layer and deconv_layer in this repository, it is easier to fit the sizes of tensors when you chose the input-figure-size as 2^n x 2^m. So, for MNIST, it maybe helps you to reshape inputs into 32x32x1.

Anyway, I'd like to make a CNN version!
