### ISSUE TITLE
Question about length of labels list

### ISSUE THREAD

**Issue by mszeto715** [takat0m0/AAE#5]
Hi,

I have another question (Thanks for responding!)

Why is the length of y one greater than the number of labels ?

**Comment by takat0m0** [comment]
Hi,

When I made these codes, I wanted to expand these to semi-supervised training.
We need another class for unlabeled data in semi-supervised training with AAE
(please see the section 2.3 in the original paper https://arxiv.org/pdf/1511.05644.pdf).
Then y has 11 labels in this implementation.
However, I only made for supervised cases....
So the other label is not used in this implementation.

**Comment by mszeto715** [comment]
Oh. Nice. Thanks again!
